services:
  lo3-bot:
    container_name: lo3-bot
    restart: unless-stopped
    build:
      context: ./..
      dockerfile: ./lo3bot/Dockerfile
    env_file:
       - '../.env'
    volumes:
      - ao3-db:/home/ao3db/
volumes:
  ao3-db:
    external: true
