services:
  lo3-bot:
    container_name: lo3-bot
    restart: unless-stopped
    build:
      context: ./..
      dockerfile: ./lo3bot/Dockerfile
    env_file:
       - '../.env'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lo3bot.rule=Host(`lo3bot.local`)"
      - "traefik.http.routers.lo3bot.entrypoints=web"
    networks:
      - traefik
