services:
    lo3-parser:
        container_name: lo3-parser
        restart: unless-stopped
        build:
            context: .
            # for mac only
            # platforms:
            #     - 'linux/amd64'
        env_file:
            - '../.env'
        ports:
            - 9000:9000
        volumes:
            - library-of-our-own_downloaded-fics:/home/downloaded-fics/
