services:
    lo3-parser:
        container_name: lo3-parser
        restart: unless-stopped
        build:
            context: .
            # for mac only
            # platforms:
            #     - 'linux/amd64'
        env_file:
            - '../.env'
        # ports:
        #     - 9000:9000
        volumes:
            - downloaded-fics:/home/downloaded-fics/
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.lo3parser.rule=Host(`lo3parser.local`)"
            - "traefik.http.routers.lo3parser.entrypoints=web"
            - "traefik.http.services.lo3parser.loadbalancer.server.port=9000"
        networks:
            - traefik
